package com.accenture.challenge.franchise_management_api;

import com.accenture.challenge.franchise_management_api.application.ports.out.FranchiseRepositoryPort;
import com.accenture.challenge.franchise_management_api.application.service.FranchiseService;
import com.accenture.challenge.franchise_management_api.domain.model.Branch;
import com.accenture.challenge.franchise_management_api.domain.model.Franchise;
import com.accenture.challenge.franchise_management_api.domain.model.Product;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import reactor.core.publisher.Mono;
import reactor.test.StepVerifier;

import java.util.ArrayList;

import static org.assertj.core.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
@DisplayName("🧪 Pruebas Unitarias del Servicio de Franquicias")
class FranchiseServiceTest {

    @Mock
    private FranchiseRepositoryPort franchiseRepositoryPort;

    @InjectMocks
    private FranchiseService franchiseService;

    private Franchise testFranchise;
    private Branch testBranch;
    private Product testProduct;

    @BeforeEach
    void setUp() {
        // Configurar franquicia de prueba
        testFranchise = new Franchise();
        testFranchise.setId("franchise-001");
        testFranchise.setName("Franquicia Test");
        testFranchise.setBranches(new ArrayList<>());

        // Configurar sucursal de prueba
        testBranch = new Branch();
        testBranch.setId("branch-001");
        testBranch.setName("Sucursal Centro");
        testBranch.setProducts(new ArrayList<>());

        // Configurar producto de prueba
        testProduct = new Product();
        testProduct.setId("product-001");
        testProduct.setName("Producto Test");
        testProduct.setStock(100);
    }

    // ==================== PRUEBAS: createFranchise ====================

    @Test
    @DisplayName("✅ Debe crear una franquicia y generar ID automáticamente")
    void testCreateFranchiseWithAutoGeneratedId() {
        // Arrange
        Franchise newFranchise = new Franchise();
        newFranchise.setName("Nueva Franquicia");

        testFranchise.setId(null);
        testFranchise.setName("Nueva Franquicia");

        when(franchiseRepositoryPort.save(any(Franchise.class)))
                .thenReturn(Mono.just(testFranchise));

        // Act & Assert
        StepVerifier.create(franchiseService.createFranchise(newFranchise))
                .assertNext(result -> {
                    assertThat(result).isNotNull();
                    assertThat(result.getName()).isEqualTo("Nueva Franquicia");
                })
                .verifyComplete();

        verify(franchiseRepositoryPort, times(1)).save(any(Franchise.class));
    }

    @Test
    @DisplayName("✅ Debe crear una franquicia con ID predefinido")
    void testCreateFranchiseWithPreDefinedId() {
        // Arrange
        Franchise franchiseWithId = new Franchise();
        franchiseWithId.setId("custom-id-123");
        franchiseWithId.setName("Franquicia con ID");

        when(franchiseRepositoryPort.save(any(Franchise.class)))
                .thenReturn(Mono.just(franchiseWithId));

        // Act & Assert
        StepVerifier.create(franchiseService.createFranchise(franchiseWithId))
                .assertNext(result -> {
                    assertThat(result.getId()).isEqualTo("custom-id-123");
                    assertThat(result.getName()).isEqualTo("Franquicia con ID");
                })
                .verifyComplete();

        ArgumentCaptor<Franchise> captor = ArgumentCaptor.forClass(Franchise.class);
        verify(franchiseRepositoryPort).save(captor.capture());
        assertThat(captor.getValue().getId()).isEqualTo("custom-id-123");
    }

    // ==================== PRUEBAS: addBranchToFranchise ====================

    @Test
    @DisplayName("✅ Debe agregar una sucursal a una franquicia existente")
    void testAddBranchToFranchiseSuccess() {
        // Arrange
        Branch newBranch = new Branch();
        newBranch.setName("Nueva Sucursal");

        when(franchiseRepositoryPort.findById("franchise-001"))
                .thenReturn(Mono.just(testFranchise));
        when(franchiseRepositoryPort.save(any(Franchise.class)))
                .thenReturn(Mono.just(testFranchise));

        // Act & Assert
        StepVerifier.create(franchiseService.addBranchToFranchise("franchise-001", newBranch))
                .assertNext(result -> {
                    assertThat(result.getBranches()).isNotEmpty();
                    assertThat(result.getBranches().get(0).getName()).isEqualTo("Nueva Sucursal");
                })
                .verifyComplete();

        verify(franchiseRepositoryPort, times(1)).findById("franchise-001");
        verify(franchiseRepositoryPort, times(1)).save(any(Franchise.class));
    }

    @Test
    @DisplayName("❌ Debe fallar al agregar sucursal a franquicia inexistente")
    void testAddBranchToNonExistentFranchise() {
        // Arrange
        Branch newBranch = new Branch();
        newBranch.setName("Nueva Sucursal");

        when(franchiseRepositoryPort.findById("non-existent"))
                .thenReturn(Mono.empty());

        // Act & Assert
        StepVerifier.create(franchiseService.addBranchToFranchise("non-existent", newBranch))
                .expectError(RuntimeException.class)
                .verify();

        verify(franchiseRepositoryPort, times(1)).findById("non-existent");
        verify(franchiseRepositoryPort, never()).save(any(Franchise.class));
    }

    @Test
    @DisplayName("✅ Debe generar ID automáticamente para la sucursal si es null")
    void testAddBranchGeneratesIdIfNull() {
        // Arrange
        Branch branchWithoutId = new Branch();
        branchWithoutId.setName("Sucursal sin ID");

        when(franchiseRepositoryPort.findById("franchise-001"))
                .thenReturn(Mono.just(testFranchise));
        when(franchiseRepositoryPort.save(any(Franchise.class)))
                .thenReturn(Mono.just(testFranchise));

        // Act & Assert
        StepVerifier.create(franchiseService.addBranchToFranchise("franchise-001", branchWithoutId))
                .assertNext(result -> assertThat(result).isNotNull())
                .verifyComplete();

        ArgumentCaptor<Franchise> captor = ArgumentCaptor.forClass(Franchise.class);
        verify(franchiseRepositoryPort).save(captor.capture());
        assertThat(captor.getValue().getBranches().get(0).getId()).isNotNull();
    }

    // ==================== PRUEBAS: addProductToBranch ====================

    @Test
    @DisplayName("✅ Debe agregar un producto a una sucursal")
    void testAddProductToBranchSuccess() {
        // Arrange
        testBranch.getProducts().clear();
        testFranchise.getBranches().add(testBranch);

        Product newProduct = new Product();
        newProduct.setName("Nuevo Producto");
        newProduct.setStock(50);

        when(franchiseRepositoryPort.findById("franchise-001"))
                .thenReturn(Mono.just(testFranchise));
        when(franchiseRepositoryPort.save(any(Franchise.class)))
                .thenReturn(Mono.just(testFranchise));

        // Act & Assert
        StepVerifier.create(franchiseService.addProductToBranch("franchise-001", "branch-001", newProduct))
                .assertNext(result -> {
                    assertThat(result.getBranches().get(0).getProducts()).isNotEmpty();
                })
                .verifyComplete();

        verify(franchiseRepositoryPort, times(1)).save(any(Franchise.class));
    }

    @Test
    @DisplayName("❌ Debe fallar si la sucursal no existe")
    void testAddProductToNonExistentBranch() {
        // Arrange
        testFranchise.getBranches().clear();

        Product product = new Product();
        product.setName("Producto");

        when(franchiseRepositoryPort.findById("franchise-001"))
                .thenReturn(Mono.just(testFranchise));

        // Act & Assert
        StepVerifier.create(franchiseService.addProductToBranch("franchise-001", "non-existent", product))
                .expectError(RuntimeException.class)
                .verify();

        verify(franchiseRepositoryPort, never()).save(any(Franchise.class));
    }

    // ==================== PRUEBAS: deleteProductFromBranch ====================

    @Test
    @DisplayName("✅ Debe eliminar un producto de una sucursal")
    void testDeleteProductFromBranchSuccess() {
        // Arrange
        testBranch.getProducts().add(testProduct);
        testFranchise.getBranches().add(testBranch);

        when(franchiseRepositoryPort.findById("franchise-001"))
                .thenReturn(Mono.just(testFranchise));
        when(franchiseRepositoryPort.save(any(Franchise.class)))
                .thenReturn(Mono.just(testFranchise));

        // Act & Assert
        StepVerifier.create(franchiseService.deleteProductFromBranch("franchise-001", "branch-001", "product-001"))
                .assertNext(result -> assertThat(result).isNotNull())
                .verifyComplete();

        verify(franchiseRepositoryPort, times(1)).save(any(Franchise.class));
    }

    @Test
    @DisplayName("❌ Debe fallar si el producto no existe")
    void testDeleteNonExistentProduct() {
        // Arrange
        testFranchise.getBranches().add(testBranch);

        when(franchiseRepositoryPort.findById("franchise-001"))
                .thenReturn(Mono.just(testFranchise));

        // Act & Assert
        StepVerifier.create(franchiseService.deleteProductFromBranch("franchise-001", "branch-001", "non-existent"))
                .expectError(RuntimeException.class)
                .verify();

        verify(franchiseRepositoryPort, never()).save(any(Franchise.class));
    }

    // ==================== PRUEBAS: updateProductStock ====================

    @Test
    @DisplayName("✅ Debe actualizar el stock de un producto exitosamente")
    void testUpdateProductStockSuccess() {
        // Arrange
        testBranch.getProducts().add(testProduct);
        testFranchise.getBranches().add(testBranch);

        when(franchiseRepositoryPort.findById("franchise-001"))
                .thenReturn(Mono.just(testFranchise));
        when(franchiseRepositoryPort.save(any(Franchise.class)))
                .thenReturn(Mono.just(testFranchise));

        // Act & Assert
        StepVerifier.create(franchiseService.updateProductStock("franchise-001", "branch-001", "product-001", 250))
                .assertNext(result -> {
                    assertThat(result.getBranches().get(0).getProducts().get(0).getStock()).isEqualTo(250);
                })
                .verifyComplete();

        verify(franchiseRepositoryPort, times(1)).save(any(Franchise.class));
    }

    @Test
    @DisplayName("❌ Debe fallar si el producto no existe para actualizar stock")
    void testUpdateStockOfNonExistentProduct() {
        // Arrange
        testFranchise.getBranches().add(testBranch);

        when(franchiseRepositoryPort.findById("franchise-001"))
                .thenReturn(Mono.just(testFranchise));

        // Act & Assert
        StepVerifier.create(franchiseService.updateProductStock("franchise-001", "branch-001", "non-existent", 200))
                .expectError(RuntimeException.class)
                .verify();

        verify(franchiseRepositoryPort, never()).save(any(Franchise.class));
    }

    // ==================== PRUEBAS: getTopStockProductsByFranchise ====================

    @Test
    @DisplayName("✅ Debe obtener los productos con mayor stock por sucursal")
    void testGetTopStockProductsByFranchiseSuccess() {
        // Arrange
        Product product1 = new Product();
        product1.setId("p1");
        product1.setName("Producto 1");
        product1.setStock(100);

        Product product2 = new Product();
        product2.setId("p2");
        product2.setName("Producto 2");
        product2.setStock(250);

        testBranch.getProducts().add(product1);
        testBranch.getProducts().add(product2);
        testFranchise.getBranches().add(testBranch);

        when(franchiseRepositoryPort.findById("franchise-001"))
                .thenReturn(Mono.just(testFranchise));

        // Act & Assert
        StepVerifier.create(franchiseService.getTopStockProductsByFranchise("franchise-001"))
                .assertNext(result -> {
                    assertThat(result.getBranchName()).isEqualTo("Sucursal Centro");
                    assertThat(result.getProductName()).isEqualTo("Producto 2");
                    assertThat(result.getStock()).isEqualTo(250);
                })
                .verifyComplete();

        verify(franchiseRepositoryPort, times(1)).findById("franchise-001");
    }

    @Test
    @DisplayName("✅ Debe retornar 'Sin productos' si la sucursal no tiene productos")
    void testGetTopStockProductsWithEmptyBranch() {
        // Arrange
        testFranchise.getBranches().add(testBranch);

        when(franchiseRepositoryPort.findById("franchise-001"))
                .thenReturn(Mono.just(testFranchise));

        // Act & Assert
        StepVerifier.create(franchiseService.getTopStockProductsByFranchise("franchise-001"))
                .assertNext(result -> {
                    assertThat(result.getProductName()).isEqualTo("Sin productos");
                    assertThat(result.getStock()).isZero();
                })
                .verifyComplete();
    }

    @Test
    @DisplayName("❌ Debe fallar si la franquicia no existe")
    void testGetTopStockProductsNonExistentFranchise() {
        // Arrange
        when(franchiseRepositoryPort.findById("non-existent"))
                .thenReturn(Mono.empty());

        // Act & Assert
        StepVerifier.create(franchiseService.getTopStockProductsByFranchise("non-existent"))
                .expectError(RuntimeException.class)
                .verify();
    }

    // ==================== PRUEBAS: updateFranchiseName ====================

    @Test
    @DisplayName("✅ Debe actualizar el nombre de la franquicia")
    void testUpdateFranchiseNameSuccess() {
        // Arrange
        when(franchiseRepositoryPort.findById("franchise-001"))
                .thenReturn(Mono.just(testFranchise));
        when(franchiseRepositoryPort.save(any(Franchise.class)))
                .thenReturn(Mono.just(testFranchise));

        // Act & Assert
        StepVerifier.create(franchiseService.updateFranchiseName("franchise-001", "Nuevo Nombre"))
                .assertNext(result -> assertThat(result).isNotNull())
                .verifyComplete();

        ArgumentCaptor<Franchise> captor = ArgumentCaptor.forClass(Franchise.class);
        verify(franchiseRepositoryPort).save(captor.capture());
        assertThat(captor.getValue().getName()).isEqualTo("Nuevo Nombre");
    }

    @Test
    @DisplayName("❌ Debe fallar si la franquicia no existe")
    void testUpdateFranchiseNameNonExistent() {
        // Arrange
        when(franchiseRepositoryPort.findById("non-existent"))
                .thenReturn(Mono.empty());

        // Act & Assert
        StepVerifier.create(franchiseService.updateFranchiseName("non-existent", "Nuevo Nombre"))
                .expectError(RuntimeException.class)
                .verify();

        verify(franchiseRepositoryPort, never()).save(any(Franchise.class));
    }

    // ==================== PRUEBAS: updateBranchName ====================

    @Test
    @DisplayName("✅ Debe actualizar el nombre de la sucursal")
    void testUpdateBranchNameSuccess() {
        // Arrange
        testFranchise.getBranches().add(testBranch);

        when(franchiseRepositoryPort.findById("franchise-001"))
                .thenReturn(Mono.just(testFranchise));
        when(franchiseRepositoryPort.save(any(Franchise.class)))
                .thenReturn(Mono.just(testFranchise));

        // Act & Assert
        StepVerifier.create(franchiseService.updateBranchName("franchise-001", "branch-001", "Nueva Sucursal"))
                .assertNext(result -> assertThat(result).isNotNull())
                .verifyComplete();

        ArgumentCaptor<Franchise> captor = ArgumentCaptor.forClass(Franchise.class);
        verify(franchiseRepositoryPort).save(captor.capture());
        assertThat(captor.getValue().getBranches().get(0).getName()).isEqualTo("Nueva Sucursal");
    }

    @Test
    @DisplayName("❌ Debe fallar si la sucursal no existe")
    void testUpdateBranchNameNonExistent() {
        // Arrange
        testFranchise.getBranches().add(testBranch);

        when(franchiseRepositoryPort.findById("franchise-001"))
                .thenReturn(Mono.just(testFranchise));

        // Act & Assert
        StepVerifier.create(franchiseService.updateBranchName("franchise-001", "non-existent", "Nuevo Nombre"))
                .expectError(RuntimeException.class)
                .verify();

        verify(franchiseRepositoryPort, never()).save(any(Franchise.class));
    }

    // ==================== PRUEBAS: updateProductName ====================

    @Test
    @DisplayName("✅ Debe actualizar el nombre del producto")
    void testUpdateProductNameSuccess() {
        // Arrange
        testBranch.getProducts().add(testProduct);
        testFranchise.getBranches().add(testBranch);

        when(franchiseRepositoryPort.findById("franchise-001"))
                .thenReturn(Mono.just(testFranchise));
        when(franchiseRepositoryPort.save(any(Franchise.class)))
                .thenReturn(Mono.just(testFranchise));

        // Act & Assert
        StepVerifier.create(franchiseService.updateProductName("franchise-001", "branch-001", "product-001", "Nuevo Producto"))
                .assertNext(result -> assertThat(result).isNotNull())
                .verifyComplete();

        ArgumentCaptor<Franchise> captor = ArgumentCaptor.forClass(Franchise.class);
        verify(franchiseRepositoryPort).save(captor.capture());
        assertThat(captor.getValue().getBranches().get(0).getProducts().get(0).getName()).isEqualTo("Nuevo Producto");
    }

    @Test
    @DisplayName("❌ Debe fallar si el producto no existe")
    void testUpdateProductNameNonExistent() {
        // Arrange
        testBranch.getProducts().add(testProduct);
        testFranchise.getBranches().add(testBranch);

        when(franchiseRepositoryPort.findById("franchise-001"))
                .thenReturn(Mono.just(testFranchise));

        // Act & Assert
        StepVerifier.create(franchiseService.updateProductName("franchise-001", "branch-001", "non-existent", "Nuevo Nombre"))
                .expectError(RuntimeException.class)
                .verify();

        verify(franchiseRepositoryPort, never()).save(any(Franchise.class));
    }
}

